### ISSUE TITLE
refactor API calls in ipns-site-generator

### ISSUE THREAD

**Issue by tx0c** [thematters/ipns-site-generator#149]
References:

1. https://github.com/ned14/static-website-activitypub
2. https://jasonrbriggs.com/journal/2023/05/08/activitypub-on-a-static-site.html
3. https://paul.kinlan.me/adding-activity-pub-to-your-static-site/
4. https://socialhub.activitypub.rocks/t/static-file-activitypub/2785
5. https://github.com/RangerMauve/staticpub.mauve.moe/

**Comment by robertu7** [comment]
https://github.com/thematters/ipns-site-generator/pull/154
